# datasets
train_file:
  - /datasets01/nlvr/061217/train/train.json'
val_file:
  - /datasets01/nlvr/061217/dev/dev.json'
test_file:
  - /datasets01/nlvr/061217/test/test.json'
image_root: /datasets01/nlvr/061217/

# image properties
image_res: 384
batch_size: 16 

# others
bert_config: configs/config_bert.json

alpha: 0.4
distill: True
warm_up: True
eval_ema: False

optimizer:
  opt: adamW
  lr: 2e-5
  weight_decay: 0.02
schedular:
  sched: cosine
  lr: 2e-5
  epochs: 10
  min_lr: 1e-6
  decay_rate: 1
  warmup_lr: 1e-5
  warmup_epochs: 1
  cooldown_epochs: 0
